export const FORTUNES: string[] = [
  'The knot will hold better when nobody is trying to win.',
  "Someone's laugh will be the safest sound in the field.",
  'Your next yes may arrive wearing muddy boots.',
  'The rope does not care how impressive you are. It cares how present you become.',
  'A soft boundary spoken early will save the whole night.',
  'You will find a doorway where you expected a schedule.',
  'The fire will not explain the lesson. It will simply wait until you understand.',
  'A whispered "no" can be the most beautiful magic in the circle.',
  'The best trouble starts with consent and ends with snacks.',
  'You are closer to the strange creature inside you than you think.',
  'Someone will see your nervousness and call it cute. They may be right.',
  'The night will reward your honesty, but not your hurry.',
  'Rope is patient. Try learning from it.',
  'You will be offered something tender. Do not grab. Receive.',
  'A muddy path may lead to a very clean truth.',
  'The portal likes people who bring their own cup.',
  'Desire is not a demand. It is a candle. Hold it carefully.',
  'You will discover that "maybe" is not confusion. It is a doorway with hinges.',
  'The most dangerous creature at camp is poor communication. Avoid feeding it.',
  "Someone's hands will ask better questions than their mouth.",
  'The forest has accepted weirder things than you. Relax.',
  'A beautiful scene may begin with "Can we slow down?"',
  'You are allowed to be wanted without being available.',
  'The best ritual is the one your body still remembers on Monday.',
  'Glitter fades. Good aftercare lingers.',
  'You will find softness in someone who looked like thunder.',
  'A clear question will save you three hours of awkward telepathy.',
  'The stars approve of negotiated filth.',
  "Someone's offering is not yours until they choose you back.",
  'You will not miss the real magic by resting. Rest is part of the spell.',
  'A head torch in the dark may reveal more than just tent pegs.',
  "The rope will not make you honest, but it will notice when you aren't.",
  'You came with expectations. Leave with better questions.',
  'Someone will thank you for stopping. Believe them.',
  'The camp remembers what you give freely.',
  'You may enter as a rigger, bottom, switch, creature, witness, or confused goblin. All are valid passports.',
  'The hottest words tonight may be "Do you want a blanket?"',
  'Your body is not a project. It is the place where the story happens.',
  "A small kindness near the kitchen may become someone's favorite memory.",
  "Don't chase the perfect scene. Follow the honest one.",
  'The portal opens wider for those who clean up after themselves.',
  'You will find a sacred moment between the soup and the shadows.',
  'If the rope tangles, flirt with the chaos.',
  'A true yes has heat. Wait for it.',
  'Someone will be brave enough to be awkward first. It might be you.',
  'The fire eats what you release and gives back light.',
  'You are not here to perform your freedom. You are here to feel it.',
  'The right invitation will feel less like pressure and more like breath.',
  'Tonight, a boundary will become a bridge.',
  'The camp will end. The opening inside you may not.',
  'The rope will not tell you who you are. It will make it harder to keep pretending.',
  'Someone near the fire will understand you before you explain yourself.',
  'A quiet yes will change the shape of your whole evening.',
  'The portal opens for those who arrive with curiosity and clean intentions.',
  'You will leave something behind without noticing. Good.',
  'A hand on your shoulder will feel like a small spell.',
  'Tonight, the best scene may begin with laughter and bad posture.',
  'Your body already knows the way. Your brain may catch up later.',
  'A stranger will become less strange after one honest question.',
  'The knot you remember most will not be the clever one.',
  "Someone's no will make the room safer. Thank them.",
  'You will be witnessed without being consumed.',
  'The fire will keep one secret for you.',
  'A soft thing will be braver than a loud thing.',
  'You came for rope. You may find a doorway.',
  'The best offering is the one freely given, freely refused, and still warm.',
  'Beware of beautiful people with head torches and emotional availability.',
  'Your tent knows more about your desires than your calendar does.',
  "Tonight's magic requires water, snacks, consent, and one reckless bit of honesty.",
  'Someone will ask clearly. Someone will answer truthfully. The gods will approve.',
  'The forest accepts your weirdness. Try doing the same.',
  'Not every invitation is for you. The right ones will still find you.',
  'The body says yes in whispers before the mouth dares.',
  'You will discover that awkwardness is just intimacy in work boots.',
  'A small ritual will hit harder than expected.',
  'The stars are not watching. Tie anyway.',
  'You will receive more by performing less.',
  "Someone's desire will look ordinary until it is spoken out loud.",
  'The night rewards those who check in before leaning closer.',
  'You are not late. The portal opens when you arrive.',
  'The best connection today may start with "maybe."',
  'There is power in asking. There is power in waiting.',
  'You will not need to be impressive to be wanted nearby.',
  'The rope is only the beginning. The real knot is attention.',
  'Your softness will survive the campsite.',
  'A creature in glitter will tell you something painfully true.',
  'The hottest thing at camp remains enthusiastic consent and decent hydration.',
  'If you lose your cup, follow the trail of bad decisions and fairy lights.',
  'Someone will offer exactly what you did not know you needed.',
  'Desire becomes safer when it is allowed to stay tender.',
  'You will be invited. You are still allowed to choose.',
  'A moment of silence will say more than the entire schedule.',
  'The campfire will make philosophers of the filthy and poets of the tired.',
  'You will meet a version of yourself that packs lighter.',
  'The most sacred tool today may be a blanket, a snack, or a very clear boundary.',
  'Let the scene end before the truth does.',
  'What you give with choice returns as warmth.',
  'Your next adventure begins with "May I?"',
  'The portal does not close. It follows you home quietly.',
  'You will return different. Not fixed. Not finished. More real.',
  'A goblin will approve of your boundary, but only after inspecting your cup.',
  'The rope knows what you did last summer. It forgives you, mostly.',
  'Beware the third fairy light after midnight. It has opinions.',
  'Your tent zipper will reveal your true spiritual alignment.',
  "A damp sock may become the oracle you didn't ask for.",
  'The forest has filed a complaint about your flirting technique.',
  'Someone in glitter will offer you soup. This is legally a prophecy.',
  'The portal opens only after you misplace something important but emotionally symbolic.',
  'A knot will whisper, "Again, but weirder."',
  'Your head torch will illuminate one practical object and three unresolved desires.',
  'The mud accepts all confessions, especially badly timed ones.',
  'If a troll asks for aftercare, bring snacks and eye contact.',
  'The stars are not judging you. The folding chair might be.',
  'You will meet a creature who smells like campfire, consent, and questionable decisions.',
  'The next person who says "quick scene" is lying to themselves and the moon.',
  'A wooden pole will become important. Do not ask how.',
  'Your future contains rope, soup, and a surprisingly meaningful spreadsheet.',
  'The fire will eat your fear, then demand marshmallows.',
  'A fairy will steal your lighter and return with emotional insight.',
  'If the blanket pile moves, negotiate first.',
  'Your deepest truth may arrive dressed as a mosquito bite.',
  'The sacred goblin inside you wants hydration and praise.',
  'Someone\'s "maybe" will hatch into a tiny dragon of clarity.',
  'The camp map is accurate, except for the horny dimension.',
  'A lost spoon will guide you toward unexpected intimacy.',
  'Do not trust the seductive rustle near the snack table. Or do. With consent.',
  'The portal has noticed your outfit and will discuss it with the moss.',
  'You will discover a new kink: correctly labelled extension cords.',
  'The moon accepts bribes in cheese, secrets, and soft moans.',
  'When in doubt, ask the mushroom. Then ask the person.',
];
